### ISSUE TITLE
how to use wasmer as a third party library using bazel?

### ISSUE THREAD

**Issue by joehattori** [wasmerio/wasmer-go#259]
### Summary
I failed to integrate wasmer-go to other project using bazel, both from remote and local.
Could anyone solve this?

### Additional details

I am trying to use wasmer-go as a third party library but have a problem with bazel build.
The project (let me call it project X) I am trying to integrate wasmer-go to uses bazel. I added following lines to `WORKSPACE` of project X
```
go_repository(
  name = "com_github_wasmer_go",
  importpath = "github.com/wasmerio/wasmer-go",
  commit = "..."
)
```
and I added the following line to `deps` in corresponding `BUILD` file where a Go file importing wasmer-go exists
```
"@com_github_wasmer_go//wasmer:go_default_library"
```
 but still get this error
```
ERROR: .... no such package '@com_github_wasmer_go//wasmer': BUILD file not found in directory 'wasmer' of external repository @com_github_wasmer_go. Add a BUILD file to a directory to mark it as a package. and referenced by ....
```
I see `wasmer/` directory doesn't have `BUILD` file as this error says. Could you tell me how to fix this error?

P.S.
I cloned wasmer-go to local and I changed the `BUILD` file of wasmer-go to
```
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/wasmerio/wasmer-go
gazelle(name = "gazelle")

package(default_visibility = ["//visibility:public"])
```
and ran `bazel run gazelle`, and then modified the `WORKSPACE` and `BUILD` file of the project X to use the local wasmer-go. Now I get this strange error when I compile with `bazel build <target>`
```
Use --sandbox_debug to see verbose messages from the sandbox
<file>: undefined: wasmer.Instance
<file>: undefined: wasmer.NewEngine
...
compilepkg: error running subcommand external/go_sdk/pkg/tool/linux_amd64/compile: exit status 2
```

**Comment by joehattori** [comment]
Even when I forked this repository and deleted `BUILD` and `WORKSPACE` file ([here](https://github.com/joehattori/wasmer-go/tree/748d49627985e5943cbac7524670db9135ad3862)) and treat it as a non-Bazel repository, I still get this error
```
Use --sandbox_debug to see verbose messages from the sandbox
<file>.go: undefined: wasmer.Instance
<file>.go: undefined: wasmer.NewEngine
<file>.go: undefined: wasmer.NewStore
```

**Comment by joehattori** [comment]
solved with https://github.com/bazelbuild/rules_go/issues/2861

**Comment by Hywan** [comment]
Hello @joehattori,

Do we need to do something on our side to fix Bazel?

**Comment by joehattori** [comment]
@Hywan Currently this repository has `BUILD` file and `WORKSPACE` file, but it is not sufficient to build wasmer-go with bazel.
I think it is good to fix bazel support or remove `BUILD` and `WORKSPACE`.

**Comment by Hywan** [comment]
Bazel support has been introduced in #106 and #108 by a contributor, but I'm not familiar with Bazel at all. If you're willing to submit a PR, I would gladly accept it!

**Comment by joehattori** [comment]
@Hywan I'm looking into it, but maybe it takes some time. I'll submit a PR when I'm done!
